### ISSUE TITLE
Any chances for this library to use lcobucci 3.4 or 4?

### ISSUE THREAD

**Issue by fd6130** [AzimoLabs/apple-sign-in-php-sdk#14]
Because my project dependencies depend on `^3.4|^4.0` so i can't use this library for my project.

And i know this is huge breaking change if this library switch to latest lcobucci : (

**Comment by hywak** [comment]
There is a fork with PHP 8 support. There were made changes required to update lcobucci to 4.0. There is a plan to migrate to 4.0 but the problem is missing resources. 

Feel free to make a pull request with updating the lib to use lcobucci 4.0. I'd appreciate that a lot.

https://github.com/AzimoLabs/apple-sign-in-php-sdk/issues/10

**Comment by fd6130** [comment]
Alright, i will use the fork first.
