### ISSUE TITLE
Unsupported cryptographic algorithm

### ISSUE THREAD

**Issue by tthlan** [AzimoLabs/apple-sign-in-php-sdk#26]
I have error frequently 30% happen at 1st time sign with apple
"Cryptographic algorithm `W6WcOKB` is not supported. Supported algorithms: `86D88Kf,eXaunmL,YuyXoY`"

I use your lib code for Apple Sign feature!
Next times when I revoke apple id on app and sign again 2nd, it could be passed.

**Comment by hywak** [comment]
Hey @tthlan, thank you for reporting the issue. Which version of the app do you use? Lately, we have released changes that removed algorithm validation. Here is a [discussion](https://github.com/AzimoLabs/apple-sign-in-php-sdk/pull/22#commitcomment-64802277) about that issue and the [PR](https://github.com/AzimoLabs/apple-sign-in-php-sdk/pull/25). Since release [2.2.0](https://github.com/AzimoLabs/apple-sign-in-php-sdk/tree/2.2.0) this exception will not be thrown.

**Comment by tthlan** [comment]
I using version 2.0.2 in my package
So I need update it I think so ... Thank for your reply

{
            "name": "azimolabs/apple-sign-in-php-sdk",
            "version": "2.0.2",
            "source": {
                "type": "git",
                "url": "https://github.com/AzimoLabs/apple-sign-in-php-sdk.git",
                "reference": "5f090539d1e02ecd9538e3025bce3bf6a3b26e47"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/AzimoLabs/apple-sign-in-php-sdk/zipball/5f090539d1e02ecd9538e3025bce3bf6a3b26e47",
                "reference": "5f090539d1e02ecd9538e3025bce3bf6a3b26e47",
                "shasum": ""
            },
            "require": {
                "ext-mbstring": "*",
                "ext-openssl": "*",
                "guzzlehttp/guzzle": "^6.0|^7.0",
                "lcobucci/jwt": "^4.0",
                "php": "^7.4 || ^8.0",
                "phpseclib/phpseclib": "^3.0"
            },
            "require-dev": {
                "mockery/mockery": "^1.4",
                "phpunit/phpunit": "^9"
            },
            "type": "library",
            "autoload": {
                "psr-4": {
                    "Azimo\\Apple\\": "src/"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Michal Baran",
                    "email": "baranmichal91@gmail.com",
                    "role": "Developer"
                }
            ],
            "description": "Library to verify and validate Apple IdentityToken and authenticate a user with Apple ID.",
            "keywords": [
                "Apple authentication",
                "Apple log in",
                "apple",
                "apple id",
                "apple sign in"
            ],
            "time": "2021-10-29T07:47:01+00:00"
        }

**Comment by hywak** [comment]
As far as I know, there were no breaking changes. The update should go smoothly. I am not going to close this issue for some time. Please let me know in a few weeks or a month whether the problem was solved.

**Comment by tthlan** [comment]
I want to confirm 1st point my double check after I update lasted AzimoLab v2.2.0 my api check token on web is success.
My team will check more  apple sign form app tomorrow. As soon as it will be passed ... I will confirm to close my ticket.
Thank for all your supports

P/s: I know I am not be alone with developing Sign with Apple Feature any more ... I am fighting it it ;-( on Symfony and Apple Developer config & documents ... , and days by days success with AzimoLabs Team's lib as my 3rd party vendor code.

**Comment by tthlan** [comment]
Hi Hywak ... Confirm it work well so far !

**Comment by guanhui07** [comment]
hi, I got the same problem 
```
Cryptographic algorithm `fh6Bs8C` is not supported. Supported algorithms: `86D88Kf,eXaunmL,YuyXoY`
```

my php version  php7.3

and 

the package version 

```
   "azimolabs/apple-sign-in-php-sdk": "^1.4"
```

**Comment by guanhui07** [comment]
supupported ,modify this class  

```php
<?php declare(strict_types=1);

namespace Azimo\Apple\Api\Enum;

class CryptographicAlgorithmEnum
{
    public const KID_86D88KF = '86D88Kf';

    public const KID_EXAUNML = 'eXaunmL';

    public const KID_YUYXOY = 'YuyXoY';
    // add this two line code
    public const KID_MY = 'fh6Bs8C';
    public const KID_MY2 = 'W6WcOKB';

    public static function supportedAlgorithms(): array
    {
        return [
            self::KID_86D88KF,
            self::KID_EXAUNML,
            self::KID_YUYXOY,
            // add this two line code
            self::KID_MY,
            self::KID_MY2,
        ];
    }

    public static function isSupported(string $algorithm): bool
    {
        return in_array($algorithm, self::supportedAlgorithms(), true);
    }
}

```

**Comment by hywak** [comment]
Hey @guanhui07,
Thank you for raising this issue. The unsupported algorithm problem is a known bug. However, it wasn't fixed in all versions yet. I assume that you are using version `1.4.x` because of your PHP version, right?

Depending on your PHP version you can either use `1.5.1` if your PHP version is `>= 7.4 < 8.0`. If you must stick to `1.4.x` I recommend you to submit a Pull Request analogous to [this one](https://github.com/AzimoLabs/apple-sign-in-php-sdk/pull/25/files). Please, checkout from [v1.4.x](https://github.com/AzimoLabs/apple-sign-in-php-sdk/tree/v1.4.x) (It's VERY important), nad request merge to `v1.4.x` branch. I will create a new release for you and you could simply bump your version.
